version: '3'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  bot:
    build: .
    environment:
      - PROD=1
    depends_on:
      - mongodb

volumes:
  dbdata6:  